parameters:
    svaroh_js_form_validator.twig_extension.class: Svaroh\JsFormValidatorBundle\Twig\Extension\JsFormValidatorTwigExtension
    svaroh_js_form_validator.factory.class: Svaroh\JsFormValidatorBundle\Factory\JsFormValidatorFactory
    svaroh_js_form_validator.extension.class: Svaroh\JsFormValidatorBundle\Form\Extension\FormExtension

services:
    svaroh_js_form_validator.twig_extension:
        class: '%svaroh_js_form_validator.twig_extension.class%'
        arguments:
            - '@svaroh_js_form_validator.factory'
        tags:
            - { name: twig.extension }

    svaroh_js_form_validator.extension:
        class: '%svaroh_js_form_validator.extension.class%'
        arguments:
            - '@svaroh_js_form_validator.factory'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    svaroh_js_form_validator.factory:
        class: '%svaroh_js_form_validator.factory.class%'
        arguments:
            - '@validator'
            - '@translator'
            - '@router'
            - '%svaroh_js_form_validator.config%'
            - '%validator.translation_domain%'

    Svaroh\JsFormValidatorBundle\Controller\AjaxController:
        public: true
        arguments:
            - '@?doctrine'
            - '@?validator'
        tags:
            - { name: controller.service_arguments }
